### ISSUE TITLE
eplorapalermo: limitare il massimo livello di zoom

### ISSUE THREAD

**Issue by aborruso** [SiciliaHub/mappe#3]
@gbvitrano bloccherei il massimo livello di zoom a 17 ([qui](http://siciliahub.github.io/mappe/eplorapalermo/#17/38.11200/13.35326) un esempio).

Oltre non si guadagna chissà che cosa, 17 mi sembra quello giusto.

**Comment by gbvitrano** [comment]
Sono d'accordo, modificato a 17
