### ISSUE TITLE
atlante pa: aggiungere URL della cartella github con il codice

### ISSUE THREAD

**Issue by aborruso** [SiciliaHub/mappe#4]
@gbvitrano nell'altlante della cartografia storica di Palermo, nel tab info, aggiungerei i riferimenti alla [cartella github](https://github.com/SiciliaHub/mappe/tree/gh-pages/atlante_carto_pa).

**Comment by gbvitrano** [comment]
Si la aggiungo, ma c'è l'icona di github in bella vista sulla sidebar. Ma ho lasciato per errore il link alla mia cartella mappe. Correggo...

**Comment by gbvitrano** [comment]
Corretto il link sull'icona di ghihub ed inserito nella scheda **informazioni** le indicazioni sul repo SiciliaHub/mappe
